from tkinter import *
from tkinter import ttk
from tkinter.ttk import Checkbutton

window = Tk()
window.title("Умный дом")
window.geometry('800x500')
tab_control = ttk.Notebook(window)

chk1_state = BooleanVar()
chk2_state = BooleanVar()
chk3_state = BooleanVar()
chk4_state = BooleanVar()
chk5_state = BooleanVar()
chk6_state = BooleanVar()
chk7_state = BooleanVar()
chk8_state = BooleanVar()
chk9_state = BooleanVar()
chk10_state = BooleanVar()
chk11_state = BooleanVar()
chk12_state = BooleanVar()
tab1 = ttk.Frame(tab_control)
tab2 = ttk.Frame(tab_control)
tab3 = ttk.Frame(tab_control)
tab4 = ttk.Frame(tab_control)
tab5 = ttk.Frame(tab_control)
tab6 = ttk.Frame(tab_control)

tab_control.add(tab1, text='Кухня')
tab_control.add(tab2, text='Ванна')
tab_control.add(tab3, text='Зал')
tab_control.add(tab4, text='Гостинная')
tab_control.add(tab5, text='Прихожия')
tab_control.add(tab6, text='Спальня')

lbl1 = Checkbutton(tab1, text='Центрально освещение', var=chk1_state)
lbl1.place(x= 250, y= 20)
lbl1 = Checkbutton(tab1, text='Боковое освещение', var=chk2_state)
lbl1.place(x= 250, y= 60)
lbl1 = Button(tab1, background="#250", text='вкл')
lbl1.place(x= 20, y= 20)
lbl1 = Button(tab1, background="#249",text='выкл')
lbl1.place(x= 20, y= 60)
lbl1=Scale(tab1, label ="Яркость света", from_ = 0, to = 100, orient =HORIZONTAL, length = 100, width = 50)
lbl1.place(x= 100, y= 10)

lbl2 = Checkbutton(tab2, text='Центрально освещение', var=chk3_state)
lbl2.place(x= 250, y= 20)
lbl2 = Checkbutton(tab2, text='Боковое освещение', var=chk4_state)
lbl2.place(x= 250, y= 60)
lbl2 = Button(tab2,background="#250", text='вкл')
lbl2.place(x= 20, y= 20)
lbl2 = Button(tab2,background="#249", text='выкл')
lbl2.place(x= 20, y= 60)
lbl2=Scale(tab2, label ="Яркость света", from_ = 0, to = 100, orient =HORIZONTAL, length = 100, width = 50)
lbl2.place(x= 100, y= 10)

lbl3 = Checkbutton(tab3, text='Центрально освещение', var=chk5_state)
lbl3.place(x= 250, y= 20)
lbl3 = Checkbutton(tab3, text='Боковое освещение', var=chk6_state)
lbl3.place(x= 250, y= 60)
lbl3 = Button(tab3,background="#250", text='вкл')
lbl3.place(x= 20, y= 20)
lbl3 = Button(tab3,background="#249", text='выкл')
lbl3.place(x= 20, y= 60)
lbl3=Scale(tab3, label ="Яркость света", from_ = 0, to = 100, orient =HORIZONTAL, length = 100, width = 50)
lbl3.place(x= 100, y= 10)

lbl4 = Checkbutton(tab4, text='Центрально освещение', var=chk7_state)
lbl4.place(x= 250, y= 20)
lbl4 = Checkbutton(tab4, text='Боковое освещение', var=chk8_state)
lbl4.place(x= 250, y= 60)
lbl4 = Button(tab4,background="#250", text='вкл')
lbl4.place(x= 20, y= 20)
lbl4 = Button(tab4,background="#249", text='выкл')
lbl4.place(x= 20, y= 60)
lbl4=Scale(tab4, label ="Яркость света", from_ = 0, to = 100, orient =HORIZONTAL, length = 100, width = 50)
lbl4.place(x= 100, y= 10)

lbl5 = Checkbutton(tab5, text='Центрально освещение', var=chk9_state)
lbl5.place(x= 250, y= 20)
lbl5 = Checkbutton(tab5, text='Боковое освещение', var=chk10_state)
lbl5.place(x= 250, y= 60)
lbl5 = Button(tab5,background="#250", text='вкл')
lbl5.place(x= 20, y= 20)
lbl5 = Button(tab5,background="#249", text='выкл')
lbl5.place(x= 20, y= 60)
lbl5=Scale(tab5, label ="Яркость света", from_ = 0, to = 100, orient =HORIZONTAL, length = 100, width = 50)
lbl5.place(x= 100, y= 10)

lbl6 = Checkbutton(tab6, text='Центрально освещение', var=chk11_state)
lbl6.place(x= 250, y= 20)
lbl6 = Checkbutton(tab6, text='Боковое освещение', var=chk12_state)
lbl6.place(x= 250, y= 60)
lbl6 = Button(tab6,background="#250", text='вкл')
lbl6.place(x= 20, y= 20)
lbl6 = Button(tab6,background="#249", text='выкл')
lbl6.place(x= 20, y= 60)
lbl6=Scale(tab6, label ="Яркость света", from_ = 0, to = 100, orient =HORIZONTAL, length = 100, width = 50)
lbl6.place(x= 100, y= 10)


tab_control.pack(expand=1, fill='both')
window.mainloop()
